{{- range $path, $_ := .Files.Glob "files/*.yaml" }}
{{- $values := $.Files.Get $path | fromYaml }}
---
apiVersion: addons.drycc.cc/v1
kind: AddonClass
metadata:
  name: {{ $values.chart }}
  labels:
    app.kubernetes.io/name: {{ $values.chart }}
    app.kubernetes.io/component: addonclass
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "3"
    helm.sh/hook-delete-policy: before-hook-creation
spec:
  description: {{ $values.description | quote }}
  displayName: {{ default $values.description $values.displayName | quote }}
  targetResource:
    apiVersion: addons.drycc.cc/v1
    kind: {{ $values.kind }}
  plans:
{{- range $values.plans }}
    - name: {{ .name | quote }}
      displayName: {{ default .description .displayName | quote }}
      enforcedValues:
{{ .enforcedValues | toYaml | indent 8 }}
      createDefaults:
{{ .createDefaults | toYaml | indent 8 }}
      allowCreatePathFields:
{{ .allowCreatePathFields | toYaml | indent 8 }}
      allowUpdatePathFields:
{{ .allowUpdatePathFields | toYaml | indent 8 }}
{{- end }}
{{- end }}
