apiVersion: v1
kind: Secret
metadata:
  name: {{ include "valkey.name" . }}-connection
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "valkey.labels" . | nindent 4 }}
type: Opaque
stringData:
  host: valkey-{{ include "valkey.name" . }}.{{ .Release.Namespace }}.svc
  port: "6379"
  {{- if .Values.users }}
  {{- if gt (len .Values.users) 0 }}
  {{- $user := index .Values.users 0 }}
  username: {{ $user.name | quote }}
  {{- if $user.passwordSecret }}
  {{- $secret := lookup "v1" "Secret" .Release.Namespace $user.passwordSecret.name }}
  {{- if $secret }}
  {{- $key := index $user.passwordSecret.keys 0 }}
  password: {{ index $secret.data $key | b64dec | quote }}
  {{- end }}
  {{- end }}
  {{- end }}
  {{- end }}
  {{- if .Values.tls.enabled }}
  tls: "true"
  {{- end }}
