apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: addonclasses.addons.drycc.cc
spec:
  group: addons.drycc.cc
  scope: Cluster
  names:
    plural: addonclasses
    singular: addonclass
    kind: AddonClass
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          required: [spec]
          properties:
            spec:
              type: object
              required: [displayName, targetResource, plans]
              properties:
                description:
                  type: string
                  minLength: 1
                  maxLength: 512
                displayName:
                  type: string
                  minLength: 1
                  maxLength: 128
                targetResource:
                  type: object
                  required: [apiVersion, kind]
                  properties:
                    apiVersion:
                      type: string
                      minLength: 1
                    kind:
                      type: string
                      minLength: 1
                    metadata:
                      type: object
                      x-kubernetes-preserve-unknown-fields: true
                plans:
                  type: array
                  minItems: 1
                  items:
                    type: object
                    required:
                      - name
                      - displayName
                      - enforcedValues
                      - createDefaults
                      - allowCreatePathFields
                      - allowUpdatePathFields
                    properties:
                      name:
                        type: string
                        minLength: 1
                        maxLength: 64
                      displayName:
                        type: string
                        minLength: 1
                        maxLength: 128
                      enforcedValues:
                        type: object
                        x-kubernetes-preserve-unknown-fields: true
                      createDefaults:
                        type: object
                        x-kubernetes-preserve-unknown-fields: true
                      allowCreatePathFields:
                        type: array
                        items:
                          type: string
                          minLength: 1
                      allowUpdatePathFields:
                        type: array
                        items:
                          type: string
                          minLength: 1
      subresources:
        status: {}
      additionalPrinterColumns:
        - name: Target
          type: string
          jsonPath: .spec.targetResource.kind
        - name: Plans
          type: integer
          jsonPath: .spec.plans.size()
