{{- if and .Values.service.enabled .Values.service.ports }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "generic.name" . }}-connection
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "generic.labels" . | nindent 4 }}
type: Opaque
stringData:
  host: {{ include "generic.fullname" . }}.{{ .Release.Namespace }}.svc
  port: {{ (index .Values.service.ports 0).port | quote }}
  {{- if .Values.ports }}
  containerPort: {{ (index .Values.ports 0).containerPort | quote }}
  {{- end }}
{{- end }}
